### ISSUE TITLE
Where can the webitel AppImage be downloaded?

### ISSUE THREAD

**Issue by probonopd** [kovalyshyn/archrice#1]
https://github.com/kovalyshyn/archrice/blob/eed7eaa81ee8d81c4d2b3f2c82ca9603f73ec595/.config/i3/config#L256

Where can the webitel AppImage be downloaded?

**Comment by kovalyshyn** [comment]
I have added URL as a comment in the i3 config file: http://phone.webitel.com

But this client works only with Webitel server: www.webitel.com

**Comment by probonopd** [comment]
Thank you.
